bash scripts_gpu/latency_test_conv.sh
bash scripts_gpu/latency_test_conv_avg.sh
# bash scripts_gpu/latency_test_conv_hosvd.sh
# bash scripts_gpu/latency_test_conv_svd.sh
bash scripts_gpu/latency_test_conv_hosvd_one_component.sh
bash scripts_gpu/latency_test_conv_svd_one_component.sh